# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

  - task: JFrogNuGet@1
    inputs:
      command: 'restore'
      artifactoryConnection: 'v2-hts'
      targetResolveRepo: 'pruthvi-nuget'
      solutionPath: '**/*.sln'
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
      includeEnvVars: true
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'v2-hts'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
